apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-go-basic3-o6yi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-go-basic3-o6yi
    app.kubernetes.io/part-of: jan7-go-forked
  name: devfile-sample-go-basic3-o6yi
  namespace: mreid1-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: devfile-sample-go-basic3-o6yi
status:
  loadBalancer: {}
